<a href="https://colab.research.google.com/github/echozhang77777/paper-daily/blob/main/Numpy_%26_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

运算速度快：numpy 和 pandas 都是采用 C 语言编写, pandas 又是基于 numpy, 是 numpy 的升级版本。\
消耗资源少：采用的是矩阵运算，会比 python 自带的字典或者列表快好多

In [1]:
import numpy as np

In [6]:

array = np.array([[1,2,3],[4,5,6]])
print(array)
print('number of dim:', array.ndim)
print('shape:',array.shape)
print('size:',array.size)

[[1 2 3]
 [4 5 6]]
number of dim: 2
shape: (2, 3)
size: 6


np中创建各种数组

In [21]:
#使用list创建
a = np.array([2,3,4])
print(a) #array结果没有逗号

a = np.array([2,3,4],dtype=np.integer)
print(a.dtype) #设置数据类型

#定义多维array
a = np.array([[2,3,4],
              [3,4,5]])
#全0矩阵
a = np.zeros((3,4))
print(a)
#全1矩阵
a = np.ones((3,4),dtype=np.integer)
print(a)
#全空矩阵
a = np.empty((3,4))
print(a)

#数列
a = np.arange(10,20,2)
print(a)

a = np.arange(10,20,1).reshape((2,5))
print(a)

#线段
a = np.linspace(1,10,5)
print(a)

[2 3 4]
int64
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[10 12 14 16 18]
[[10 11 12 13 14]
 [15 16 17 18 19]]
[ 1.    3.25  5.5   7.75 10.  ]


/tmp/ipykernel_1148/1474445047.py:5: DeprecationWarning: Converting `np.integer` or `np.signedinteger` to a dtype is deprecated. The current result is `np.dtype(np.int_)` which is not strictly correct. Note that the result depends on the system. To ensure stable results use may want to use `np.int64` or `np.int32`.
  a = np.array([2,3,4],dtype=np.integer)


np的基础运算

In [33]:
a = np.array([10,20,30,40])
b = np.arange(4)
print(a,b)

c = a - b
print(c)

c = b**2
print(c)

#三角函数
c = 10*np.sin(a)
print(c)
#判断array与某个值的大小
print(b<3)
print(b==3)
#运算矩阵
a = np.array([[1,1],
              [0,1]])
b = np.arange(4).reshape((2,2))
print(a)
print(b)
c = a*b #对应位置,逐个相乘
print(c)
c_dot = np.dot(a,b) #矩阵乘法
#上式等价于c_dot = a.dot(b)
print(c_dot)
#随机产生矩阵
a = np.random.random((2,4)) #(0,1)之间的数据
print(a)
#sum
print(np.sum(a))
print(np.min(a))
print(np.max(a))
#axis 可选某个维度下的最大值或最小值 axis=0是行,axis=1是列.
print(np.sum(a,axis=1))

[10 20 30 40] [0 1 2 3]
[10 19 28 37]
[0 1 4 9]
[-5.44021111  9.12945251 -9.88031624  7.4511316 ]
[ True  True  True False]
[False False False  True]
[[1 1]
 [0 1]]
[[0 1]
 [2 3]]
[[0 1]
 [0 3]]
[[2 4]
 [2 3]]
[[0.54202935 0.92618972 0.11556294 0.18709424]
 [0.80064436 0.86882666 0.49640551 0.14406195]]
4.0808147394971535
0.11556294098820341
0.9261897185547434
[1.77087625 2.30993848]


Numpy的基础运算2\
索引

In [50]:
a = np.arange(2,14).reshape(3,4)
print(a)

print(np.argmin(a))
print(np.argmax(a))

#计算数列的均值
print(np.mean(a))
print(a.mean())
print(np.average(a))
#中位数
print(np.median(a))
#数据累加
print(np.cumsum(a))
#数据累差
print(np.diff(a))
#找非0
print(np.nonzero(a)) #输出值的行数和列数
#sort
print(np.sort(a))
#计算矩阵相乘
print(np.transpose(a))
print(a.T)
#CLIP
print(np.clip(a,5,9)) #小于5就等于5,大于9就给9
print(np.mean(a,axis=0)) #对行求均值


[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
0
11
7.5
7.5
7.5
7.5
[ 2  5  9 14 20 27 35 44 54 65 77 90]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]
[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]
[[5 5 5 5]
 [6 7 8 9]
 [9 9 9 9]]
[6. 7. 8. 9.]


Numpy的索引

In [63]:
#一维
a = np.arange(3,15)
print(a)
print(a[3])
#二维
a = np.arange(3,15).reshape(3,4)
print(a)
print(a[2])
print(a[1,1])
print(a[1][1])
print(a[2,:])
print(a[:,1])
print(a[1,1:2])
#for 循环
#迭代行
for row in a:
  print(row)
#迭代列
for column in a.T:
  print(column)
#展平
print(a.flatten()) #返回一个被改变的flatten
for item in a.flat:
  print(item)

[ 3  4  5  6  7  8  9 10 11 12 13 14]
6
[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[11 12 13 14]
8
8
[11 12 13 14]
[ 4  8 12]
[8]
[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]
[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14


Numpy的array合并

In [72]:
a = np.array([1,1,1])
b = np.array([2,2,2])

#上下合并
print(np.vstack((a,b))) #vertical stack
print(np.vstack((a,b)).shape)
print(a.shape)
#横向合并
print(np.hstack((a,b))) #horizontal stack
print(np.hstack((a,b)).shape)
#横向数列转纵向数列
#transpose做不到
print(a[np.newaxis,:])
print(a[np.newaxis,:].shape)
print(a[:,np.newaxis])
print(a[:,np.newaxis].shape)

#多项合并
a = np.array([1,1,1])
b = np.array([2,2,2])
c = np.concatenate((a,b,b,a),axis=0)
print(c)

[[1 1 1]
 [2 2 2]]
(2, 3)
(3,)
[1 1 1 2 2 2]
(6,)
[[1 1 1]]
(1, 3)
[[1]
 [1]
 [1]]
(3, 1)
[1 1 1 2 2 2 2 2 2 1 1 1]


Numpy的array的分割

In [78]:
a = np.arange(12).reshape(3,4)
print(a)

print(np.split(a,2,axis=1))
#不等分割,split会报错
#print(np.split(a,3,axis=1))
#不等量分割
print(np.array_split(a,3,axis=1)) #加一个array就可以成功不等分割
#横向分割
print(np.vsplit(a,3))
#纵向分割
print(np.hsplit(a,2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


numpy的copy和deep copy

In [90]:
a = np.arange(4)
b = a
c = a
d = b
a[0] = 11
a
b is a #a中数据改变也意味着b c d中的数据改变
d is a

#如何不要关联另外的变量
b = a.copy() #deep copy
a[3] = 44
print(b)
print(a)
b is a


[11  1  2  3]
[11  1  2 44]


False

# Pandas的基本介绍
更像是字典类型的numpy

In [91]:
import pandas as pd


In [ ]:
s = pd.Series([1,2,3,6,np.nan,44,1])
s

In [105]:
dates = pd.date_range('20160101',periods=6)
dates

df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=['a','b','c','d'])
df

df1 = pd.DataFrame(np.arange(12).reshape(3,4))
df1

df2 = pd.DataFrame({'A':1.,
                    'B':pd.Timestamp('20130102'),
                    'C':pd.Series(1,index=list(range(4)),dtype='float32'),
                    'D':np})
df2
df2.dtypes
df2.index
df2.columns
df2.values
df2.describe()
df2.T
df2.sort_index(axis=1,ascending=False)
df2.sort_values(by='B')


,A,B,C,D
0,1.0,2013-01-02,1.0,<module 'numpy' from '/usr/local/lib/python3.1...
1,1.0,2013-01-02,1.0,<module 'numpy' from '/usr/local/lib/python3.1...
2,1.0,2013-01-02,1.0,<module 'numpy' from '/usr/local/lib/python3.1...
3,1.0,2013-01-02,1.0,<module 'numpy' from '/usr/local/lib/python3.1...


Pandas选择数据

In [8]:
import pandas as pd
import numpy as np
dates = pd.date_range('20160101',periods=6)
dates

df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=['a','b','c','d'])
df

print(df['a'])
print(df.a)
print(df[0:3])
print(df['20160102':'20160104'])

#selected by label: loc
print(df.loc['20160102'])
print(df.loc[:,['a','b']])
print(df.loc['20160102',['a','b']])

#selected by position: iloc
print(df.iloc[3])
print(df.iloc[3,1])
print(df.iloc[3:5,1:3])
print(df.iloc[[1,2,4],[1,2]])

#mixed selection: ix
#print(df.ix[:3,['a','c']])
#新版本已经删除了ix

#Boolean indexing
print(df[df.a>0])
print(df[df>0])



2016-01-01   -0.441058
2016-01-02   -0.322124
2016-01-03   -0.562268
2016-01-04    2.168327
2016-01-05    0.401654
2016-01-06    0.576239
Freq: D, Name: a, dtype: float64
2016-01-01   -0.441058
2016-01-02   -0.322124
2016-01-03   -0.562268
2016-01-04    2.168327
2016-01-05    0.401654
2016-01-06    0.576239
Freq: D, Name: a, dtype: float64
                   a         b         c         d
2016-01-01 -0.441058  2.007729  0.304527  1.558244
2016-01-02 -0.322124 -0.323418 -0.179965  0.099293
2016-01-03 -0.562268 -1.102725  0.292623 -0.424390
                   a         b         c         d
2016-01-02 -0.322124 -0.323418 -0.179965  0.099293
2016-01-03 -0.562268 -1.102725  0.292623 -0.424390
2016-01-04  2.168327  0.441405 -1.290597 -0.309248
a   -0.322124
b   -0.323418
c   -0.179965
d    0.099293
Name: 2016-01-02 00:00:00, dtype: float64
                   a         b
2016-01-01 -0.441058  2.007729
2016-01-02 -0.322124 -0.323418
2016-01-03 -0.562268 -1.102725
2016-01-04  2.168327  0.4414

In [9]:
#Boolean indexing
print(df[df.a <8])

                   a         b         c         d
2016-01-01 -0.441058  2.007729  0.304527  1.558244
2016-01-02 -0.322124 -0.323418 -0.179965  0.099293
2016-01-03 -0.562268 -1.102725  0.292623 -0.424390
2016-01-04  2.168327  0.441405 -1.290597 -0.309248
2016-01-05  0.401654  1.745228 -0.513063 -0.074292
2016-01-06  0.576239  2.256886  0.896583  0.788248


pandas设置值

In [12]:
dates = pd.date_range('20130101',periods=6)
df = pd.DataFrame(np.arange(24).reshape((6,4)),index=dates,columns=['A','B','C','D'])
df

df.iloc[2,2] = 1111
df.loc['20130101','B'] = 2222
df

df[df.A>4] = 0
print(df)

df['F'] = np.nan
df['E'] = pd.Series([1,2,3,4,5,6],index=pd.date_range('20130101',periods=6))
print(df)

            A     B  C  D
2013-01-01  0  2222  2  3
2013-01-02  4     5  6  7
2013-01-03  0     0  0  0
2013-01-04  0     0  0  0
2013-01-05  0     0  0  0
2013-01-06  0     0  0  0
            A     B  C  D   F  E
2013-01-01  0  2222  2  3 NaN  1
2013-01-02  4     5  6  7 NaN  2
2013-01-03  0     0  0  0 NaN  3
2013-01-04  0     0  0  0 NaN  4
2013-01-05  0     0  0  0 NaN  5
2013-01-06  0     0  0  0 NaN  6


pandas处理丢失数据

In [14]:
dates = pd.date_range('20130101',periods=6)
df = pd.DataFrame(np.arange(24).reshape((6,4)),index=dates,columns=['A','B','C','D'])
df


df.iloc[1,2] = np.nan
df.iloc[2,3] = np.nan
df
#删除nan
print(df.dropna(axis=0,how='any')) #how={'all','any'}
print(df.dropna(axis=1,how='any'))

#填补为某个数字
print(df.fillna(value=0))

#检查是否为nan
print(df.isnull())
print(np.any(df.isnull()) == True)

             A   B     C     D
2013-01-01   0   1   2.0   3.0
2013-01-04  12  13  14.0  15.0
2013-01-05  16  17  18.0  19.0
2013-01-06  20  21  22.0  23.0
             A   B
2013-01-01   0   1
2013-01-02   4   5
2013-01-03   8   9
2013-01-04  12  13
2013-01-05  16  17
2013-01-06  20  21
             A   B     C     D
2013-01-01   0   1   2.0   3.0
2013-01-02   4   5   0.0   7.0
2013-01-03   8   9  10.0   0.0
2013-01-04  12  13  14.0  15.0
2013-01-05  16  17  18.0  19.0
2013-01-06  20  21  22.0  23.0
                A      B      C      D
2013-01-01  False  False  False  False
2013-01-02  False  False   True  False
2013-01-03  False  False  False   True
2013-01-04  False  False  False  False
2013-01-05  False  False  False  False
2013-01-06  False  False  False  False
True


pandas导入导出

In [ ]:
data = pd.read_csv('student.csv')
print(data)
data.to_pickle('student.pickle')

pandas合并concat

In [ ]:
#concatenating
df1 = pd.DataFrame(np.ones((3,4))*0,columns=['a','b','c','d'])
df2 = pd.DataFrame(np.ones((3,4))*1,columns=['a','b','c','d'])
df3 = pd.DataFrame(np.ones((3,4))*2,columns=['a','b','c','d'])
print(df1)
print(df2)
print(df3)

#上下合并
res = pd.concat([df1,df2,df3],axis=0) #axis=0,竖向,axis=1,横向.
print(res)

res = pd.concat([df1,df2,df3],axis=0,ignore_index=True) #重排纵向
print(res)

#join,{'inner','outer'}
df1 = pd.DataFrame(np.ones((3,4))*0,columns=['a','b','c','d'],index=[1,2,3])
df2 = pd.DataFrame(np.ones((3,4))*1,columns=['b','c','d','e'],index=[2,3,4])
print(df1)
print(df2)
#有共同也有不同
res = pd.concat([df1,df2],join='outer') #outer是默认的
print(res)
res = pd.concat([df1,df2],join='inner',ignore_index=True)
print(res)


pandas合并merge
https://www.bilibili.com/video/av16378934?spm_id_from=333.788.videopod.episodes&aid=16378934&vd_source=350008e04b05acfa2a11acf18e65282c&p=17

pandas plot画图